name: Release
on:
 push:
  branches: [feature/release-workflow]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # - name: Run semantic-release
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_version }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create ZIP
        run: |
          zip -r package-${VERSION}.zip dist/
      - name: Upload ZIP to GitHub Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          files: akamai-insights-datasource-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
